[package]
name = "openredirect"
version = "0.1.0"
edition = "2021"

[dependencies]

reqwest = { version = "0.11", features = ["blocking"] }  
colored = "2.0"                                         
url = "2.2"    
